### ISSUE TITLE
The buttons perform their action twice

### ISSUE THREAD

**Issue by AlisterH** [mach0/themeselector#2]
The buttons to add, rename and duplicate themes all seem to perform their action twice.  i.e. I am asked twice what I want to call the theme.
QGIS 3.8.0

**Comment by mach0** [comment]
Cannot confirm here.
May I ask for your OS and a complete description what you are doing?

**Comment by AlisterH** [comment]
Sorry - Windows 10, but after restarting QGIS it seems to be fixed.  
I will report if I can reproduce again.  Do you want to close the ticket?

BTW I then uninstalled the plugin and reinstalled to see if it only happens after install, and the reinstall didn't work properly (the ThemeSelector panel wouldn't display) until I restarted QGIS... not sure if that is a QGIS problem or a problem with the plugin.

**Comment by mach0** [comment]
that rather sounds like a QGIS problem - loading and unloading plugin (or better installing and uninstalling) is nothing I can control.
Closing for now - please reopen when reproduceable.
