### ISSUE TITLE
Menu entry differs from plugin name.

### ISSUE THREAD

**Issue by AlisterH** [mach0/themeselector#3]
It seems strange that the plugin inserts itself in the menu under "Presetter", when the plugin name is "ThemeSelector".  Wouldn't it be better to be consistent?

**Comment by mach0** [comment]
Thanks a lot. Seems that was a leftover in translation Files from the "coding" name ;)
Will be fixed in next release.

**Comment by mach0** [comment]
should have been already solved - but now for sure ;)
