### ISSUE TITLE
Implementation request

### ISSUE THREAD

**Issue by hudjinn** [mach0/themeselector#5]
First i would like to thank you for the wonderful plugin. Congratulations to everyone involved!
I would humbly ask to insert a shortcut or shortcut button customization to switch between themes. Thanks!

**Comment by mach0** [comment]
hi and thanks for your comment.
As there are literally endless themes to create I am not quite sure what you want to achieve with a shortcut.
So could you please explain a bit more detailed how you imagine a shortcut implemented?

**Comment by hudjinn** [comment]
Thanks for the reply. ThemeSelect was the best and most practical way we found to change the active layers in the work we developed. it is a work with a lot of comparison between images and layers, but they are necessarily two distinct themes that we keep exchanging between them. A shortcut (eg CTRL + Up arrow and CTRL + Down arrow) to change between presets would be awesome

**Comment by hudjinn** [comment]
Thanks a lot!
