### ISSUE TITLE
If duplicating or renaming, the dialog appeared five times

### ISSUE THREAD

**Issue by velle** [mach0/themeselector#6]
This just happened, many times in a theme, but now I cant replicate it. 

Whenever I renamed or duplicated a theme, a small dialog box would appear, to let me type the name. No matter what I entered, and no matter if I pressed Ok or Cancel, the dialog would close and another one appear. Every time, I had to handle exactly five dialog boxes :)

I closed and reopened QGIS, and the issue was gone.

**Comment by mach0** [comment]
Hi and thanks for reporting.
I have a few changes that might address the issue, but to be honest - I have had the same problem - and could not replicate it.

**Comment by mach0** [comment]
this problem should be fixed with the new release
