### ISSUE TITLE
Does not properly refresh the combo menu

### ISSUE THREAD

**Issue by velle** [mach0/themeselector#7]
If I add a theme with the regular Layers window, the plugin does not notice and refresh/update. This new layer wont be shown until I manipulate the layers via the plugin, eg by adding a new layer. 

Using QGIS version 3.24.3-Tisler on Ubuntu.

**Comment by mach0** [comment]
wontfix as long as there is no signal emmited to python when a theme is added renamed or deleted

**Comment by nicogodet** [comment]
@mach0 According to https://qgis.org/pyqgis/master/core/QgsMapThemeCollection.html, these signals exist

- https://qgis.org/pyqgis/master/core/QgsMapThemeCollection.html#qgis.core.QgsMapThemeCollection.mapThemeRenamed
- https://qgis.org/pyqgis/master/core/QgsMapThemeCollection.html#qgis.core.QgsMapThemeCollection.mapThemesChanged
